// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/proto/merchant/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,4,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	LegalName     string                 `protobuf:"bytes,5,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	DbaName       string                 `protobuf:"bytes,7,opt,name=dba_name,json=dbaName,proto3" json:"dba_name,omitempty"`
	TaxId         string                 `protobuf:"bytes,8,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStoreRequest) Reset() {
	*x = RegisterStoreRequest{}
	mi := &file_shared_proto_merchant_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStoreRequest) ProtoMessage() {}

func (x *RegisterStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_merchant_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStoreRequest.ProtoReflect.Descriptor instead.
func (*RegisterStoreRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_merchant_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterStoreRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RegisterStoreRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *RegisterStoreRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *RegisterStoreRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *RegisterStoreRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *RegisterStoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterStoreRequest) GetDbaName() string {
	if x != nil {
		return x.DbaName
	}
	return ""
}

func (x *RegisterStoreRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

type RegisterStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	DisplayId     string                 `protobuf:"bytes,2,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Plan          string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStoreResponse) Reset() {
	*x = RegisterStoreResponse{}
	mi := &file_shared_proto_merchant_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStoreResponse) ProtoMessage() {}

func (x *RegisterStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_merchant_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStoreResponse.ProtoReflect.Descriptor instead.
func (*RegisterStoreResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_merchant_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterStoreResponse) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *RegisterStoreResponse) GetDisplayId() string {
	if x != nil {
		return x.DisplayId
	}
	return ""
}

func (x *RegisterStoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterStoreResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

var File_shared_proto_merchant_merchant_proto protoreflect.FileDescriptor

const file_shared_proto_merchant_merchant_proto_rawDesc = "" +
	"\n" +
	"$shared/proto/merchant/merchant.proto\x12\bmerchant\"\xff\x01\n" +
	"\x14RegisterStoreRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12#\n" +
	"\rmobile_number\x18\x04 \x01(\tR\fmobileNumber\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x05 \x01(\tR\tlegalName\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\bdba_name\x18\a \x01(\tR\adbaName\x12\x15\n" +
	"\x06tax_id\x18\b \x01(\tR\x05taxId\"}\n" +
	"\x15RegisterStoreResponse\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"display_id\x18\x02 \x01(\tR\tdisplayId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan2c\n" +
	"\x0fMerchantService\x12P\n" +
	"\rRegisterStore\x12\x1e.merchant.RegisterStoreRequest\x1a\x1f.merchant.RegisterStoreResponseBCZAgithub.com/moneymate-2026/moneymate-backend/shared/proto/merchantb\x06proto3"

var (
	file_shared_proto_merchant_merchant_proto_rawDescOnce sync.Once
	file_shared_proto_merchant_merchant_proto_rawDescData []byte
)

func file_shared_proto_merchant_merchant_proto_rawDescGZIP() []byte {
	file_shared_proto_merchant_merchant_proto_rawDescOnce.Do(func() {
		file_shared_proto_merchant_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_merchant_merchant_proto_rawDesc), len(file_shared_proto_merchant_merchant_proto_rawDesc)))
	})
	return file_shared_proto_merchant_merchant_proto_rawDescData
}

var file_shared_proto_merchant_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_merchant_merchant_proto_goTypes = []any{
	(*RegisterStoreRequest)(nil),  // 0: merchant.RegisterStoreRequest
	(*RegisterStoreResponse)(nil), // 1: merchant.RegisterStoreResponse
}
var file_shared_proto_merchant_merchant_proto_depIdxs = []int32{
	0, // 0: merchant.MerchantService.RegisterStore:input_type -> merchant.RegisterStoreRequest
	1, // 1: merchant.MerchantService.RegisterStore:output_type -> merchant.RegisterStoreResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_merchant_merchant_proto_init() }
func file_shared_proto_merchant_merchant_proto_init() {
	if File_shared_proto_merchant_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_merchant_merchant_proto_rawDesc), len(file_shared_proto_merchant_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_merchant_merchant_proto_goTypes,
		DependencyIndexes: file_shared_proto_merchant_merchant_proto_depIdxs,
		MessageInfos:      file_shared_proto_merchant_merchant_proto_msgTypes,
	}.Build()
	File_shared_proto_merchant_merchant_proto = out.File
	file_shared_proto_merchant_merchant_proto_goTypes = nil
	file_shared_proto_merchant_merchant_proto_depIdxs = nil
}
